name: ci
on: [push, pull_request]
env:
  CLANG_TIDY_VERSION: "15.0.0"

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2022
        compiler:
          - llvm-13.0.0
          - msvc
        generator:
          - "Ninja Multi-Config"
        build_type:
          - Release
          - Debug
        #developer_mode:
        #  - ON
        #  - OFF

        exclude:
          # mingw is too buggy to support
          - os: windows-2022
            compiler: gcc-11

          # exclude msvc on non-windows
          - os: ubuntu-20.04
            compiler: msvc
          - os: macos-10.15
            compiler: msvc

    steps:
      - name: test
        run: echo "::debug test message env.CLANG_TIDY_VERSION"