name: clang-format check
on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clang-format src
      if: ${{ always() }}
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        check-path: 'src'
        # exclude: '(hello|world)' # Exclude file paths containing "hello" or "world"
        exclude-regex: ''        
    - name: clang-format test
      if: ${{ always() }}
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        check-path: 'test'
        exclude-regex: ''
